# Generated by Django 4.0.7 on 2023-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneitas', '0004_etiqueta_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('incomplete', 'TO DO'), ('complete', 'Done')], max_length=10)),
            ],
        ),
    ]
